# Generated by Django 3.1.3 on 2020-11-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('integer', models.BigIntegerField()),
                ('range_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('range_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_separator', models.CharField(blank=True, choices=[(',', ','), ('.', '.')], max_length=10, null=True)),
                ('string_character', models.CharField(blank=True, choices=[('"', '"'), ("/'", "/'")], max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('modified', models.DateField(auto_now_add=True)),
                ('rows', models.PositiveSmallIntegerField()),
                ('creator', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_type', models.CharField(blank=True, choices=[('full_name_type', 'Full name'), ('integer_type', 'Integer'), ('job_type', 'Job'), ('company_name_type', 'Company name'), ('date_type', 'Date')], max_length=20, null=True)),
                ('column_name', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.fakedata', verbose_name='')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.schema', verbose_name='')),
            ],
        ),
    ]
