# Generated by Django 3.1.3 on 2020-11-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnitem',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.fakedata', verbose_name='FakeData'),
        ),
        migrations.AlterField(
            model_name='columnitem',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.schema', verbose_name='Schema'),
        ),
    ]
