# Generated by Django 3.1.3 on 2020-11-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20201121_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='title',
            new_name='name',
        ),
    ]
