# Generated by Django 3.1.3 on 2020-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20201121_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakedata',
            name='order',
        ),
        migrations.AddField(
            model_name='columnitem',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
