# Generated by Django 3.1.3 on 2020-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20201121_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
