# Generated by Django 3.1.3 on 2020-11-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20201121_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnitem',
            name='range_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='columnitem',
            name='range_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
