# Generated by Django 3.1.3 on 2020-11-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20201121_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnitem',
            name='data',
        ),
        migrations.DeleteModel(
            name='FakeData',
        ),
    ]
