# Generated by Django 3.1.3 on 2020-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_auto_20201121_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(blank=True, choices=[(',', 'Comma (,)'), ('.', 'Dot (.)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(blank=True, choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")], max_length=50, null=True),
        ),
    ]
