# Generated by Django 3.1.3 on 2020-11-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20201121_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(blank=True, choices=[('Double-quote (")', 'Double-quote (")'), ("Single-quote (')", "Single-quote (')")], max_length=50, null=True),
        ),
    ]
