# Generated by Django 3.1.3 on 2020-11-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_auto_20201121_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(blank=True, choices=[('Comma (,)', 'Comma (,)'), ('Dot (.)', 'Dot (.)')], max_length=50, null=True),
        ),
    ]
