# Generated by Django 3.1.3 on 2020-11-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_auto_20201121_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='file_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Processing', 'Processing'), ('Create', 'Create')], default='Create', max_length=20),
        ),
    ]
