# Generated by Django 3.1.3 on 2020-11-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_auto_20201121_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnitem',
            name='column_type',
            field=models.CharField(blank=True, choices=[('Full name', 'Full name'), ('Integer', 'Integer'), ('Job', 'Job'), ('Company name', 'Company name'), ('Date', 'Date')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='columnitem',
            name='range_from',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='columnitem',
            name='range_to',
            field=models.PositiveIntegerField(blank=True, default=2147483647, null=True),
        ),
    ]
