# Generated by Django 3.1.3 on 2020-11-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_auto_20201122_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='status',
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('rows', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Processing', 'Processing'), ('Create', 'Create')], default='Create', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=100, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.schema', verbose_name='Schema')),
            ],
        ),
    ]
